{
    "name": "Aktiv PMS",
    "category": "Services/Project",
    "author": "Aktiv Software",
    "version": "19.0.1.0.0",
    "license": "OPL-1",
    "depends": ["project", "hr_timesheet", "analytic", "ak_crm","ak_public_holidays"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/ir_cron_data.xml",
        "data/task_type_data.xml",
        "data/default_res_config.xml",
        "views/project_views.xml",
        "views/project_task.xml",
        "wizard/project_task_wizard.xml",
        "wizard/functional_wizard.xml",
        "views/basic_guideline_views.xml",
        "data/mail_template.xml",
        "views/quality_check_views.xml",
        "wizard/quality_check_points_wizard_views.xml",
        "data/month_weekday.xml",
        "data/month_date.xml",
        "views/aktiv_meetings.xml",
        "views/meeting_mom.xml",

        "wizard/meeting_mom_wizard.xml",
        "wizard/meeting_reschedule_wizard.xml",
        "wizard/meeting_cancellation_wizard.xml",
        "wizard/pms_basic_guideline_mail_wizard.xml",

        "views/meeting_agenda.xml",
        "views/hr_timesheet.xml",
        "views/res_users_view.xml",
        "views/res_config_settings.xml",
        "views/quality_analysis_views.xml",
        "views/urgent_task_views.xml",
        "views/knowledge_bank.xml",
        "views/task_type_views.xml",
        "report/report_timesheet_template.xml",
        "wizard/create_project_pms.xml",
    ],
    'external_dependencies': {
        'python': ['OdooRPC'],
    },
    "assets": {
        "web.assets_backend": [
            "aktiv_pms/static/src/css/style.css",
            'aktiv_pms/static/src/legacy/js/fields/*',
            'aktiv_pms/static/src/legacy/scss/*',
            'aktiv_pms/static/src/legacy/xml/field_productive_logs.xml',
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
