from . import crm_lead
from . import crm_stage
from . import res_partner
from . import odoo_version
from . import technology
from . import crm_type
from . import mail_thread
from . import mail_mail
from . import mail_message
