{
    "name": "Aktiv CRM",
    "category": "Services/Project",
    "author": "Aktiv Software",
    "version": "19.0.1.0.0",
    "license": "OPL-1",
    "depends": ["crm", "mail"],
    "data": [
        "data/crm_type.xml",
        "data/crm_stage.xml",
        "data/crm_technology.xml",
        "data/mail_data.xml",
        "data/sequence.xml",
        "data/action_server.xml",
        "data/mail_template.xml",
        "security/ir.model.access.csv",
        "security/crm_security.xml",
        "wizard/chatter_send_mail_views.xml",
        "wizard/crm_lead_to_opportunity.xml",
        "views/crm_menu_views.xml",
        "views/crm_stage_views.xml",
        "views/crm_lead_views.xml",
        "views/res_partner_views.xml",
        "views/odoo_version.xml",
        "views/technology.xml",
        "views/crm_type.xml",
        "views/mail_mail.xml",
        "wizard/crm_lead_lost_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ak_crm/static/src/chatter/web/chatter.js",
            "ak_crm/static/src/chatter/web/chatter.xml",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
